# Elixir CircleCI 2.0 configuration file
# Check https://circleci.com/docs/2.0/language-elixir/ for more details
version: 2.1
jobs:
  mix_tests:
    docker:
      - image: circleci/elixir:1.11.3-node
        environment:
          MIX_ENV: test

    working_directory: ~/repo
    steps:
      - checkout

      - run: mkdir ./tmp
      - run: mix local.hex --force
      - run: mix local.rebar --force
      - run: mix do setup, deps.compile, compile
      - run: mix coveralls.json -o ./tmp

      - store_test_results:
          path: ./tmp
  docker_test:
    machine:
      image: ubuntu-2004:202101-01

    steps:
      - checkout

      - run: docker build -t openfn-microservice .
      - run: | 
          docker run --rm \
            -e HOST_URL=localhost \
            -e PORT=4000 \
            -e ENDPOINT_STYLE=sync \
            -e MIX_ENV=prod \
            -e PROJECT_DIR=/opt/app/project \
            -e SECRET_KEY_BASE=72\/yhPGEs8\/dfRio2Xw0HDjVT+tE587rc+hf4i6dNIIUbtXGU5vG2t3qSHvLikFQ \
            -v $PWD/docker/example/volume:/opt/app/project \
            openfn-microservice \
            sh -c '(mix phx.server)& curl --retry 15 --retry-delay 10 --retry-all-errors http://localhost:4000 && exit 0 || exit $?'

# Orchestrate our job run sequence
workflows:
  tests:
    jobs:
      - mix_tests
      - docker_test